### ISSUE TITLE
[MiniGoal 2]add audio notifications for bad electrode connection and timers

### ISSUE THREAD

**Issue by xqu** [xqu/biofeedback#3]
add audio notifications for bad electrode connection and timers

**Comment by VenusMeow** [comment]
check the cell phone app's documentation for notification of bad connection

**Comment by xqu** [comment]
Headband Status Indicator / Horseshoe

**Comment by xqu** [comment]
http://developer.choosemuse.com/research-tools/available-data

**Comment by xqu** [comment]
main.js  line 65 , understand the 4x5 matrices, and the time stamp,

**Comment by VenusMeow** [comment]
Updates in VenusUpdate1107.zip:

I tried to add somelines in muse.js so that it will also include the data from the headband/horseshoe:
<img width="622" alt="screen shot 2017-11-07 at 1 51 02 am" src="https://user-images.githubusercontent.com/32319682/32480722-2cc50f9e-c35e-11e7-843f-40a6fa1fd6ea.png">

Haven't incorporated into main.js yet....but if you call up from main.js hopefully the data should be able to transmit...

**Comment by xqu** [comment]
http://developer.choosemuse.com/research-tools/available-data
let's always include the URL,
"Headband Status

These values can be used to determine if Muse is on the head properly and getting good contact. These values are emitted at 10Hz.

The first two could be helpful in our situation. 

Headband On / Touching Forehead"

Headband Status Indicator / Horseshoe
