### ISSUE TITLE
[MiniGoal 3]add audio notifications for reading coach feedback

### ISSUE THREAD

**Issue by xqu** [xqu/biofeedback#4]
add audio notifications for reading coach feedback

**Comment by VenusMeow** [comment]
I tried a few times, even changed the reading materials to something I know I will pay a lot attention to while reading, and even asked my roommate to read something with full focus, but the thing is, the audio will go on and on after around 40-50 seconds (with the current 1 min window setting), telling me that my brain is not on "reading mode". I'm wondering if the setting for audio cue is too hard to achieve regarding reading concentration. Or more specifically, can the cluster data for reading really represent our brains correctly? And even if I change the time window to longer or shorter periods, the audio cue still haunts me when a whole time window is nearly past. 
And just a thought in mind, could the cluster that we use for reference be modified so that it could be customized for each user?

**Comment by xqu** [comment]
um 我这边试了很多遍都发现一个问题 就是快到一个window的时间的时候就会开始不停的响那个audio cue 我都换了中文来看来确保阅读专心程度 包括换了我室友来试 都不管用 更改window的长短 从一分钟换到其他分钟也不管用 或者更改那个20%的设定 到更小甚至1% 都依然有这个问题 我这data好像就一直对不上reading的cluster 不知@Andrew 试的咋样 这一段反馈英文版 我也写在学长的github issue#4里面了

**Comment by xqu** [comment]
现在的cluster是怎么存的，我们怎么生成当前user 的cluster

**Comment by VenusMeow** [comment]
20%>1% : **muse.js line 127**
  if (window_sum<0.2*window_size){

**Comment by xqu** [comment]
two things, where Mercedes' clusters are saved now, (currently just a table)
how can we change that table for each individual user ,
we save the data, we run the K-means JavaScript library, we got a new table of clusters for the current user , we replace that table.

**Comment by xqu** [comment]
ideally it should have training period to generate each subject's own cluster.
